#!/bin/bash
# Simple build script, potentially useful if building a GPL-redistributable
# version on a system *without* SPEC CPU2017.  See:
#
#     https://www.spec.org/cpu2017/Docs/licenses.html#GPLtarballs
#
# Note: if the benchmark uses "specpp", that is the freely-redistributable
#       preprocessor "filepp".   It is described at 
#         https://www.spec.org/cpu2017/Docs/utility.html#specpp  
#       and will need to be in your path.  You can find filepp sources as
#       modified by SPEC in redistributable_sources/modified/tools.src/harness-spec.tar.xz 
#---------------------------------------------------------------------------

/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/mc.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/mc.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/predict.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/predict.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/pixel.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/pixel.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/macroblock.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/macroblock.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/frame.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/frame.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/dct.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/dct.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/cpu.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/cpu.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/cabac.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/cabac.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/common.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/common.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/mdate.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/mdate.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/rectangle.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/rectangle.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/set.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/set.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/quant.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/quant.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/deblock.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/deblock.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/vlc.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/vlc.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/common/mvpred.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/common/mvpred.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/analyse.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/analyse.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/me.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/me.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/ratecontrol.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/ratecontrol.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/set.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/set.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/macroblock.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/macroblock.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/cabac.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/cabac.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/cavlc.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/cavlc.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/encoder.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/encoder.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/encoder/lookahead.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/encoder/lookahead.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/input/timecode.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/input/timecode.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/input/yuv.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/input/yuv.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/input/y4m.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/input/y4m.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/output/raw.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/output/raw.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/output/matroska.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/output/matroska.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/output/matroska_ebml.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/output/matroska_ebml.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/output/flv.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/output/flv.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/output/flv_bytestream.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/output/flv_bytestream.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/input/thread.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/input/thread.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/x264.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/x264.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o x264_src/extras/getopt.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678             -fno-strict-aliasing   -DSPEC_LP64  x264_src/extras/getopt.c
